"""CLI smoke tests for the FINAL-A A4 frozen surface.

Frozen commands:
    pystemtc run    --config <defaults.txt> --output <dir>
    pystemtc batch  --config-dir <dir>  --output <dir>

Frozen exit codes:
    0 = success
    1 = analysis / config / I/O failure (per-config in batch mode)
    2 = CLI usage error (bad args, missing --config / --output,
       config path does not exist, etc.)

These tests exercise the CLI through :func:`pystemtc.cli.main` (the
same function pyproject.toml's ``[project.scripts]`` entry points to)
and through ``subprocess`` for the entry-point script path -- the
latter is what :pep:`518` build backends and downstream packaging
will exercise.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from pystemtc import cli


# ---------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------


def _write_c08_config(
    config_dir: Path,
    config_name: str,
    data_relpath: str = "g27_1.txt",
) -> Path:
    """Write a c08-style defaults.txt that points at the bundled g27_1.txt.

    c08 = "no repeats" -- the smallest valid run.  Path is recorded
    relative to the config file's directory to exercise the FINAL-A
    relative-path rule (CLI resolves against config_dir, not CWD).
    """
    cfg = config_dir / config_name
    cfg.write_text(
        "# generated by test_cli.py\n"
        f"Data_File\t{data_relpath}\n"
        "Normalize_Data\tNormalize data\n"
        "Spot_IDs_included_in_the_data_file\ttrue\n"
        "Maximum_Number_of_Missing_Values\t0\n"
        "Minimum_Absolute_Log_Ratio_Expression\t0.8\n"
        "Change_should_be_based_on\tDifference From 0\n"
        "Minimum_Correlation_between_Repeats\t0.0\n"
        "Repeat_Data_Files(comma delimited list)\t\n"
        "Repeat_Data_is_from\tDifferent time periods\n"
        "Clustering_Method\tSTEM Clustering Method\n"
        "Maximum_Number_of_Model_Profiles\t50\n"
        "Maximum_Unit_Change_in_Model_Profiles_between_Time_Points\t2\n"
        "Maximum_Correlation\t1.0\n"
        "Maximum_Number_of_Candidate_Model_Profiles\t1000000\n"
        "Number_of_Permutations_per_Gene\t50\n"
        "Permutation_Test_Should_Permute_Time_Point_0\ttrue\n"
        "Significance_Level\t0.05\n"
        "Correction_Method\tBonferroni\n"
        "Clustering_Minimum_Correlation\t0.7\n"
        "Clustering_Minimum_Correlation_Percentile\t0.0\n",
        encoding="utf-8",
    )
    return cfg


def _bundle_g27_1(config_dir: Path) -> Path:
    """Copy tests/golden/data/g27_1.txt next to the test config.

    The CLI resolves relative Data_File against the config's own
    directory, so each test that exercises relative-path resolution
    needs the data next to its config.
    """
    src = Path(__file__).resolve().parent / "golden" / "data" / "g27_1.txt"
    dst = config_dir / "g27_1.txt"
    if not dst.exists():
        dst.write_bytes(src.read_bytes())
    return dst


# ---------------------------------------------------------------------
# main() / cmd_run
# ---------------------------------------------------------------------


def test_cli_run_happy_path(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    config_dir = tmp_path / "cfg"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    _bundle_g27_1(config_dir)
    cfg = _write_c08_config(config_dir, "c08_run_ok.txt")

    rc = cli.main(["run", "--config", str(cfg), "--output", str(out_dir)])

    assert rc == 0
    out_lines = capsys.readouterr().out.strip().splitlines()
    # cmd_run prints the absolute paths of the two written tables
    assert len(out_lines) == 2
    assert out_lines[0].endswith("c08_run_ok_genetable.txt")
    assert out_lines[1].endswith("c08_run_ok_profiletable.txt")
    assert Path(out_lines[0]).is_file()
    assert Path(out_lines[1]).is_file()


def test_cli_run_resolves_relative_path_against_config_dir(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Even with a different CWD, the CLI must find Data_File via the config dir."""
    config_dir = tmp_path / "cfg"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    _bundle_g27_1(config_dir)
    cfg = _write_c08_config(config_dir, "c08_relpath.txt")

    other_cwd = tmp_path / "elsewhere"
    other_cwd.mkdir()
    monkeypatch.chdir(other_cwd)

    rc = cli.main(["run", "--config", str(cfg), "--output", str(out_dir)])

    assert rc == 0, capsys.readouterr().err
    assert (out_dir / "c08_relpath_genetable.txt").is_file()
    assert (out_dir / "c08_relpath_profiletable.txt").is_file()


def test_cli_run_missing_config_returns_2(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    rc = cli.main(["run", "--config", str(tmp_path / "no_such.txt"),
                   "--output", str(tmp_path / "out")])
    assert rc == 2
    assert "config not found" in capsys.readouterr().err


def test_cli_run_missing_required_arg_returns_2(
    capsys: pytest.CaptureFixture[str],
) -> None:
    rc = cli.main(["run", "--config", "x"])  # no --output
    assert rc == 2


def test_cli_run_analysis_failure_returns_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """Data_File points at a non-existent file -> analysis / I/O failure -> exit 1."""
    config_dir = tmp_path / "cfg"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    cfg = _write_c08_config(config_dir, "c08_bad.txt", data_relpath="does_not_exist.txt")

    rc = cli.main(["run", "--config", str(cfg), "--output", str(out_dir)])

    assert rc == 1
    assert "Data_File not found" in capsys.readouterr().err


def test_cli_run_empty_data_file_returns_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """Data_File empty in the config -> configuration error -> exit 1."""
    config_dir = tmp_path / "cfg"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    cfg = _write_c08_config(config_dir, "c08_empty.txt", data_relpath="")

    rc = cli.main(["run", "--config", str(cfg), "--output", str(out_dir)])

    assert rc == 1
    assert "Data_File is empty" in capsys.readouterr().err


# ---------------------------------------------------------------------
# main() / cmd_batch
# ---------------------------------------------------------------------


def test_cli_batch_happy_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    config_dir = tmp_path / "configs"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    _bundle_g27_1(config_dir)
    _write_c08_config(config_dir, "a.txt")
    _write_c08_config(config_dir, "b.txt")

    rc = cli.main(["batch", "--config-dir", str(config_dir), "--output", str(out_dir)])

    assert rc == 0
    assert (out_dir / "a_genetable.txt").is_file()
    assert (out_dir / "b_genetable.txt").is_file()


def test_cli_batch_continues_on_failure(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    """One bad config + one good config -> exit 1, but the good config still wrote."""
    config_dir = tmp_path / "configs"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    _bundle_g27_1(config_dir)

    # Sorted iteration order is alphabetical.  a_bad.txt first (fails),
    # b_good.txt second (succeeds).
    _write_c08_config(config_dir, "a_bad.txt", data_relpath="missing.txt")
    _write_c08_config(config_dir, "b_good.txt")

    rc = cli.main(["batch", "--config-dir", str(config_dir), "--output", str(out_dir)])

    assert rc == 1
    assert not (out_dir / "a_bad_genetable.txt").exists()
    assert (out_dir / "b_good_genetable.txt").is_file()
    err = capsys.readouterr().err
    assert "a_bad.txt" in err
    assert "1/2 config(s) failed" in err


def test_cli_batch_missing_dir_returns_2(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    rc = cli.main(["batch", "--config-dir", str(tmp_path / "no_such"),
                   "--output", str(tmp_path / "out")])
    assert rc == 2
    assert "config-dir not found" in capsys.readouterr().err


def test_cli_batch_empty_dir_returns_0(
    tmp_path: Path, capsys: pytest.CaptureFixture[str],
) -> None:
    rc = cli.main(["batch", "--config-dir", str(tmp_path), "--output", str(tmp_path / "out")])
    assert rc == 0
    assert "no config files" in capsys.readouterr().err


# ---------------------------------------------------------------------
# Subprocess entry-point path (what pyproject's [project.scripts] installs)
# ---------------------------------------------------------------------


def test_cli_entry_point_via_subprocess(tmp_path: Path) -> None:
    """``python -m pystemtc.cli`` must agree with the in-process main().

    FINAL-A A4 freezes ``[project.scripts] pystemtc = "pystemtc.cli:main"``.
    Without a built wheel we exercise ``python -m`` (the same function
    the entry point calls) so the test does not depend on pip install.
    """
    config_dir = tmp_path / "cfg"
    config_dir.mkdir()
    out_dir = tmp_path / "out"
    _bundle_g27_1(config_dir)
    cfg = _write_c08_config(config_dir, "c08_entry.txt")

    proc = subprocess.run(
        [sys.executable, "-m", "pystemtc.cli",
         "run", "--config", str(cfg), "--output", str(out_dir)],
        capture_output=True, text=True, env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        cwd=str(tmp_path),
    )

    assert proc.returncode == 0, proc.stderr
    assert (out_dir / "c08_entry_genetable.txt").is_file()
    assert (out_dir / "c08_entry_profiletable.txt").is_file()
