"""M2 unit tests: hand-computed / derived cases for profiles, assignment,
permutations, significance, clustering and the Java formatting replicas.

Boundary values for ``binomialtail`` come from the real JRE 8 via
``jjs`` (tests/golden/java_statutil/vectors.txt, generated by
``tools/gen_statutil_vectors.js``).
"""

import json
import math
from pathlib import Path

import numpy as np
import pytest

from pystemtc.assign import best_assignments
from pystemtc.clustering import cluster_profiles
from pystemtc.config import STEMConfig
from pystemtc.dataset import SpotSet, build_stem_dataset
from pystemtc.engine import STEM
from pystemtc.errors import STEMTCValueError
from pystemtc.javaformat import double_to_sz, java_double_to_string
from pystemtc.permutation import all_permutations, expected_counts
from pystemtc.profiles import (
    _compact_profiles2_bulk,
    _compact_profiles2_scalar,
    enumerate_candidates,
    sample_candidates,
)
from pystemtc.result import STEMResult
from pystemtc.rng import JavaRandom
from pystemtc.significance import binomial_tail, correct, logbinomcoeff
from pystemtc._stats import correlation

GOLDEN = Path(__file__).parent / "golden"
DATA = GOLDEN / "data"
VECTORS = GOLDEN / "java_statutil" / "vectors.txt"


# ---------------------------------------------------------------------------
# golden StatUtil vectors (real Java via jjs)
# ---------------------------------------------------------------------------

def _java_float(text: str) -> float:
    """Parse a Java-printed double literal ('1.0E-9', '4.5E-17', ...)."""
    return float(text.replace("E", "e"))


def test_statutil_binomialtail_golden_vectors():
    lines = VECTORS.read_text(encoding="utf-8").splitlines()
    assert len(lines) > 100
    checked = 0
    for line in lines:
        parts = line.split("\t")
        if parts[0] == "BINOMTAIL":
            x, n = int(parts[1]), int(parts[2])
            dp = _java_float(parts[3])
            want = _java_float(parts[4])
            got = binomial_tail(x, n, dp)
            assert got == want, f"binomialtail({x},{n},{dp}): {got} != {want}"
            checked += 1
        elif parts[0] == "LOGBINOM":
            ni, n = int(parts[1]), int(parts[2])
            want = _java_float(parts[3])
            got = logbinomcoeff(ni, n)
            assert got == want, f"logbinomcoeff({ni},{n}): {got} != {want}"
            checked += 1
    assert checked == len(lines)


def test_binomialtail_boundary_semantics():
    # x > N -> 0 (checked before the x++ quirk)
    assert binomial_tail(60, 10, 0.3) == 0.0
    # x < 0 (count 0: ceil(-1) = -1) -> 1
    assert binomial_tail(-1, 10, 0.3) == 1.0
    # dp <= 0 / dp >= 1 -> 1 (dp == 1 also returns 1)
    assert binomial_tail(5, 50, 0.0) == 1.0
    assert binomial_tail(5, 50, 1.0) == 1.0
    # x_orig == N quirk: x++ enters the formula producing a tiny nonzero value
    assert binomial_tail(10, 10, 0.3) == _java_float("0.0000025306714285714307")
    # interior value pinned by jjs
    assert binomial_tail(2, 10, 0.3) == _java_float("0.6172172135999991")
    # 0 < count < 1 and count == 1 both cast to x=0, then x++ -> P(X >= 1)
    from pystemtc.significance import count_pvalue
    assert count_pvalue(0.5, 10, 0.3) == count_pvalue(1.0, 10, 0.3)
    assert count_pvalue(0.5, 10, 0.3) == binomial_tail(0, 10, 0.3)


# ---------------------------------------------------------------------------
# candidate profiles
# ---------------------------------------------------------------------------

def test_enumerate_candidates_count_and_order():
    # (u=1, T=3): 3^2 = 9 candidates, the all-zero one removed -> 8
    c13 = enumerate_candidates(1, 3)
    assert len(c13) == 8
    # last column varies fastest; steps (i//3, i%3) - 1; original index 4 is zero
    assert c13[0] == [0.0, -1.0, -2.0]
    assert c13[1] == [0.0, -1.0, -1.0]
    assert c13[2] == [0.0, -1.0, 0.0]
    assert c13[3] == [0.0, 0.0, -1.0]
    assert c13[4] == [0.0, 0.0, 1.0]  # original index 5 (zero row removed)
    assert c13[7] == [0.0, 1.0, 2.0]

    # (u=2, T=4): 5^3 = 125 -> 124
    c24 = enumerate_candidates(2, 4)
    assert len(c24) == 124
    assert all(row[0] == 0.0 for row in c24)
    assert not any(all(v == 0.0 for v in row) for row in c24)


def test_compact_seed_is_monotone_profile():
    # :1582-1587 — the seed index equals the candidate index of the unit-step
    # monotone profile {0, 1, ..., T-1} for every u; the seed is the FIRST
    # selected candidate (selectedindex[0]) and therefore always among the
    # compacted profiles
    for u, T in ((1, 3), (1, 5), (2, 4), (2, 6)):
        cands = enumerate_candidates(u, T)
        models, ids = _compact_profiles2_scalar(cands, 50, 1.0, u)
        assert ids == sorted(ids)
        monotone = [float(i) for i in range(T)]
        assert monotone in models, (u, T)


def test_compact_bulk_and_scalar_agree():
    for u, T in ((1, 5), (2, 4), (2, 6)):
        cands = enumerate_candidates(u, T)
        ms, ids_s = _compact_profiles2_scalar(cands, 50, 1.0, u)
        mb, ids_b = _compact_profiles2_bulk(cands, 50, 1.0, u)
        assert ms == mb and ids_s == ids_b
    # also on a random-walk sample (includes constant candidates -> NaN paths)
    cands = sample_candidates(2, 5, 2000)
    ms, ids_s = _compact_profiles2_scalar(cands, 20, 1.0, 2)
    mb, ids_b = _compact_profiles2_bulk(cands, 20, 1.0, 2)
    assert ms == mb and ids_s == ids_b


def test_sample_candidates():
    # sample 0 is the strictly descending profile and consumes no RNG
    s = sample_candidates(2, 5, 4)
    assert s[0] == [0.0, -2.0, -4.0, -6.0, -8.0]
    # rows 1.. reproduce Random(3733246) walks step by step
    rng = JavaRandom(3733246)
    for nsample in (1, 2, 3):
        value = 0.0
        row = [0.0]
        for _ in range(4):
            value = value + math.floor(rng.next_double() * 5 - 2)
            row.append(float(value))
        assert s[nsample] == row
    # cap == 1: no RNG consumed at all
    assert sample_candidates(1, 3, 1) == [[0.0, -1.0, -2.0]]


# ---------------------------------------------------------------------------
# assignment and tally
# ---------------------------------------------------------------------------

def test_best_assignments_ties_keep_all_and_flat_gene_all_profiles():
    models = [[0.0, 1.0, 2.0], [0.0, -1.0, -2.0], [0.0, 0.0, 1.0]]
    gene_data = np.array(
        [[0.0, 1.0, 2.0], [0.0, 2.0, 4.0], [0.0, -1.0, -2.0], [0.0, 0.0, 0.0]],
        dtype=np.float64,
    )
    gene_pma = np.full((4, 3), 2, dtype=np.int8)
    best = best_assignments(gene_data, gene_pma, models)
    # row 0: identical to profile 0; profile 1 is the exact mirror (corr -1);
    # no tie with profile 0's corr 1.0
    assert best[0] == [0]
    # row 1: proportional to profile 0 -> corr 1.0, tie kept in index order
    assert best[1] == [0]
    # row 2: identical to profile 1
    assert best[2] == [1]
    # flat gene: variance 0 -> Util.correlation returns 0 for every profile
    # -> ALL profiles tie at 0 (argmax over [-2 start] -> first 0.0... all equal)
    assert best[3] == [0, 1, 2]


def _toy_dataset():
    """3 genes x 4 time points; gene B is flat (all-zero after normalize)."""
    data = np.array(
        [[1.0, 2.0, 3.0, 4.0], [5.0, 5.0, 5.0, 5.0], [2.0, 4.0, 6.0, 8.0]],
        dtype=np.float64,
    )
    pma = np.full((3, 4), 2, dtype=np.int8)
    main = SpotSet(
        raw_data=data,
        raw_pma=pma,
        spot_ids=["S1", "S2", "S3"],
        gene_ids=["A", "B", "C"],
        probe_ids=["S1", "S2", "S3"],
        sample_labels=["0h", "1h", "2h", "4h"],
    )
    cfg = STEMConfig(normalize="normalize", min_abs_expr=0.0, maxmin=False)
    return build_stem_dataset(main, [], "different_periods", cfg)


def test_engine_tally_weights_and_result():
    ds = _toy_dataset()
    engine = STEM(n_permutations=0)  # exact permutations, no RNG
    result = engine.fit(ds)
    assert isinstance(result, STEMResult)
    assert len(result.profiles) > 1
    # every gene contributes exactly 1.0 in total (1/k over its ties)
    total = sum(p.n_assigned for p in result.profiles)
    assert total == 3.0
    # the flat gene B ties with EVERY profile -> fractional 1/k weights
    flat_row = next(g for g in result.gene_assignments if g.gene == "B")
    tied_ids = [int(t) for t in flat_row.profile.split(";")]
    assert len(tied_ids) == len(result.profiles)
    expected_fraction = 1.0 / len(result.profiles)
    assert any(
        abs(p.n_assigned - expected_fraction) < 1e-12 for p in result.profiles
    )
    # genetable Profile string of the non-flat genes has no ties
    a_row = next(g for g in result.gene_assignments if g.gene == "A")
    assert ";" not in a_row.profile
    # gene A and C are proportional -> identical argmax
    c_row = next(g for g in result.gene_assignments if g.gene == "C")
    assert a_row.profile == c_row.profile


def test_engine_metadata_and_to_dict():
    ds = _toy_dataset()
    result = STEM(n_permutations=0).fit(ds)
    meta = result.metadata
    assert meta["permutation_mode"] == "exact"
    assert meta["n_permutations_requested"] == 0
    assert meta["legacy_with_replacement"] is False
    assert meta["input_form"] == "stem_dataset"
    payload = json.dumps(result.to_dict())  # JSON compatible
    assert '"profiles"' in payload and '"clusters"' in payload


def test_engine_kmeans_not_implemented():
    with pytest.raises(NotImplementedError):
        STEM(clustering_method="kmeans").fit(_toy_dataset())


# ---------------------------------------------------------------------------
# permutations
# ---------------------------------------------------------------------------

def test_all_permutations_order_and_fix_t0():
    full = all_permutations(3, fix_t0=False)
    assert full.shape == (6, 3)
    assert full.tolist() == [
        [0, 1, 2],
        [0, 2, 1],
        [1, 0, 2],
        [1, 2, 0],
        [2, 0, 1],
        [2, 1, 0],
    ]
    fixed = all_permutations(3, fix_t0=True)
    assert fixed.shape == (2, 3)
    assert fixed.tolist() == [[0, 1, 2], [0, 2, 1]]
    assert all_permutations(4, fix_t0=False).shape == (24, 4)
    assert all_permutations(4, fix_t0=True).shape == (6, 4)
    assert all_permutations(2, fix_t0=True).tolist() == [[0, 1]]


def test_expected_counts_meta_modes():
    # T=4 -> exact path with n=0 and with n >= 4!
    ds = _toy_dataset()
    models = [[0.0, 1.0, 2.0, 3.0], [0.0, -1.0, -2.0, -3.0]]
    expected, meta = expected_counts(ds, models, 0, True)
    assert meta["permutation_mode"] == "exact"
    assert meta["legacy_with_replacement"] is False
    assert meta["n_permutations_requested"] == 0
    # scaling: expected * numrows / ntotalassignments
    numrows = ds.gene_data.shape[0]
    assert all(0.0 <= v <= numrows + 1e-9 for v in expected)
    # t0 fixed: (T-1)! = 6 universe, requesting 2 -> legacy subsample path
    _, meta2 = expected_counts(ds, models, 2, False)
    assert meta2["permutation_mode"] == "subsample_universe"
    assert meta2["legacy_with_replacement"] is True
    # on-the-fly needs T >= 9: emulate via a 10-column dataset
    rng = np.random.default_rng(7)
    data = rng.normal(size=(6, 10))
    pma = np.full((6, 10), 2, dtype=np.int8)
    main = SpotSet(
        raw_data=data,
        raw_pma=pma,
        spot_ids=[f"S{i}" for i in range(6)],
        gene_ids=[f"G{i}" for i in range(6)],
        probe_ids=[f"S{i}" for i in range(6)],
        sample_labels=[str(i) for i in range(10)],
    )
    cfg = STEMConfig(normalize="none_add0", min_abs_expr=0.0, maxmin=False)
    ds10 = build_stem_dataset(main, [], "different_periods", cfg)
    models10 = [[float(i % 3 - 1) for i in range(10)]]
    _, meta3 = expected_counts(ds10, models10, 5, True)
    assert meta3["permutation_mode"] == "on_the_fly"


# ---------------------------------------------------------------------------
# multiple correction
# ---------------------------------------------------------------------------

def test_correct_fdr_walk_and_crash():
    # step-down walk: dthresh = last p_(i) < (i+1)*alpha/n; significant = p <= dthresh
    sig, pvals = correct([0.01, 0.5, 0.6], 0.1, "fdr")
    assert pvals == [0.01, 0.5, 0.6]
    assert sig == [True, False, False]  # dthresh = 0.01 (0.5 fails at i=1)
    sig2, _ = correct([0.5, 0.6, 0.7], 0.1, "fdr")
    assert sig2 == [False, False, False]  # dthresh stays 0
    # all-significant case: Java walks off pvalcopy[n] -> ArrayIndexOutOfBounds;
    # the port raises the equivalent IndexError and this is NOT fixed away
    with pytest.raises(IndexError):
        correct([0.01, 0.02, 0.03], 0.1, "fdr")


def test_correct_non_fdr_strict_and_count_rule():
    # Bonferroni: alpha/n; significant = p < threshold AND count > 1 (strict <)
    sig, _ = correct([0.005, 0.005], 0.05, "bonferroni", counts=[2.0, 1.0])
    assert sig == [True, False]  # equal threshold: strict < rejects count==1 row
    # count == threshold boundary: p == alpha/n is NOT significant (strict <)
    sig2, _ = correct([0.025, 0.024], 0.05, "bonferroni", counts=[3.0, 3.0])
    assert sig2 == [False, True]
    # none: plain alpha with the same strict < and count rule
    sig3, _ = correct([0.0499999, 0.05, 0.005], 0.05, "none", counts=[5.0, 5.0, 1.0])
    assert sig3 == [True, False, False]


# ---------------------------------------------------------------------------
# profile clustering
# ---------------------------------------------------------------------------

_A = [0.0, 1.0, 2.0, 3.0]
_B = [0.0, -3.0, 0.0, 3.0]
_C = [0.0, 0.0, 3.0, 2.0]


def test_cluster_member_rule_is_ge_threshold():
    # corr(A,B) = 0.6324..., corr(A,C) = 0.7745..., corr(B,C) = 0.5443...
    t_bc = correlation(_B, _C, [1, 1, 1, 1], [1, 1, 1, 1])
    t_ab = correlation(_A, _B, [1, 1, 1, 1], [1, 1, 1, 1])
    t_ac = correlation(_A, _C, [1, 1, 1, 1], [1, 1, 1, 1])
    assert t_ab > t_bc and t_ac > t_bc
    models = [_A, _B, _C]
    counts = [1.0, 1.0, 1.0]
    # thr == corr(B,C) exactly: B is a candidate for A's ball (t_ab > thr),
    # and as a ball member corr(B, C) == thr satisfies the >= member rule
    # (closeToAllNeighbors rejects only corr < thr), so one 3-profile cluster
    clusters = cluster_profiles([0, 1, 2], counts, models, t_bc, 0.0)
    assert clusters == [[0, 2, 1]]


def test_cluster_neighbor_rule_is_strict_gt_and_center_dist_quirk():
    # X and Y have correlation exactly 1.0
    x = [0.0, 1.0, 2.0, 3.0]
    y = [0.0, 2.0, 4.0, 6.0]
    t = correlation(x, y, [1, 1, 1, 1], [1, 1, 1, 1])
    assert t == 1.0
    counts = [2.0, 3.0]
    # thr == corr: neighbors need corr > thr -> no candidates; each center's
    # ball is itself, and Y (count 3) wins the first round (strict >)
    clusters = cluster_profiles([0, 1], counts, [x, y], t, 0.0)
    assert clusters == [[1], [0]]
    # thr slightly below: Y is a candidate of X's ball; the center X is added
    # with distance 1.0 which the TreeSet REJECTS (equal to Y's distance), so
    # the best ball is [Y] only (X not removed) and X clusters afterwards
    clusters2 = cluster_profiles([0, 1], counts, [x, y], t - 1e-9, 0.0)
    assert clusters2 == [[1], [0]]


# ---------------------------------------------------------------------------
# Java formatting replicas
# ---------------------------------------------------------------------------

def test_java_double_to_string():
    assert java_double_to_string(45.0) == "45.0"
    assert java_double_to_string(0.0) == "0.0"
    assert java_double_to_string(-0.0) == "-0.0"
    assert java_double_to_string(0.1) == "0.1"
    assert java_double_to_string(42.7) == "42.7"
    assert java_double_to_string(0.5) == "0.5"
    assert java_double_to_string(1.0 / 3.0) == "0.3333333333333333"
    assert java_double_to_string(1e7) == "1.0E7"
    assert java_double_to_string(1e-4) == "1.0E-4"
    assert java_double_to_string(1.5e-8) == "1.5E-8"
    assert java_double_to_string(1234567.0) == "1234567.0"
    assert java_double_to_string(-2.0) == "-2.0"
    assert java_double_to_string(float("nan")) == "NaN"
    assert java_double_to_string(float("inf")) == "Infinity"


def test_double_to_sz():
    assert double_to_sz(0.0) == "0.00"
    assert double_to_sz(-1.0) == "0.00"  # dval <= 0 -> "0.00"
    assert double_to_sz(1.0) == "1.00"
    assert double_to_sz(0.5) == "0.50"
    assert double_to_sz(0.38) == "0.38"
    assert double_to_sz(0.995) == "0.99"  # 0.995 binary < 0.995 decimal
    # scaling branch boundary: nexp == -2 stays plain, -3 goes scientific
    assert double_to_sz(0.0095) == "9.5E-3"
    assert double_to_sz(0.01) == "0.01"
    # small values: mantissa recomputed via Math.pow(10, log10(d)-nexp)
    assert double_to_sz(7.1e-7) == "7.1E-7"
    assert double_to_sz(1.0) == "1.00"


# ---------------------------------------------------------------------------
# config / error paths
# ---------------------------------------------------------------------------

def test_config_defaults_file_m2_keys(tmp_path):
    cfg_file = tmp_path / "d.txt"
    cfg_file.write_text(
        "Data_File\tx.txt\n"
        "Maximum_Correlation\t0.9\n"
        "Number_of_Permutations_per_Gene\t10\n"
        "Maximum_Number_of_Candidate_Model_Profiles\t2000\n"
        "Maximum_Number_of_Model_Profiles\t25\n"
        "Maximum_Unit_Change_in_Model_Profiles_between_Time_Points\t1\n"
        "Significance_Level\t0.01\n"
        "Correction_Method\tFalse Discovery Rate\n"
        "Permutation_Test_Should_Permute_Time_Point_0\tfalse\n"
        "Clustering_Minimum_Correlation\t0.8\n"
        "Clustering_Minimum_Correlation_Percentile\t0.25\n"
        "Clustering_Method\tK-means\n"
        "Repeat_Data_Files(comma delimited list)\ta.txt, b.txt\n",
        encoding="utf-8",
    )
    cfg = STEMConfig.from_defaults_file(cfg_file)
    assert cfg.max_correlation == 0.9
    assert cfg.n_permutations == 10
    assert cfg.candidate_cap == 2000
    assert cfg.max_model_profiles == 25
    assert cfg.max_unit_change == 1
    assert cfg.alpha == 0.01
    assert cfg.correction == "fdr"
    assert cfg.permute_t0 is False
    assert cfg.cluster_min_correlation == 0.8
    assert cfg.cluster_corr_percentile == 0.25
    assert cfg.clustering_method == "kmeans"
    assert cfg.repeat_files == ["a.txt", "b.txt"]
    assert cfg.data_file == "x.txt"


def test_engine_validates_profile_params():
    ds = _toy_dataset()
    with pytest.raises(STEMTCValueError):
        STEM(max_unit_change=0).fit(ds)
    with pytest.raises(STEMTCValueError):
        STEM(candidate_cap=10, max_model_profiles=50).fit(ds)
    with pytest.raises(STEMTCValueError):
        STEM(alpha=-1).fit(ds)
